#INCLUDE "rwmake.ch"

User Function PEFINREL(_aErros)


Local cDesc1        := "Este programa tem como objetivo imprimir relatorio "
Local cDesc2        := "de acordo com os parametros informados pelo usuario."
Local cDesc3        := ""
Local cPict         := ""
Local titulo       	:= "Relatorio Retorno Serasa"
Local nLin         	:= 80
                   	
Local Cabec1		:= "Duplicata Cli/Loja  Nome cliente                      Observações"
Local Cabec2       	:= "                           Detalhes erro                         "
Local imprime      	:= .T.
Local aOrd 			:= {}
Private lEnd        := .F.
Private lAbortPrint := .F.
Private CbTxt       := ""
Private limite      := 80
Private tamanho     := "P"
Private nomeprog    := "PEFINREL" 
Private nTipo       := 18
Private aReturn     := { "Zebrado", 1, "Administracao", 2, 2, 1, "", 1}
Private nLastKey    := 0
Private cbtxt      	:= Space(10)
Private cbcont     	:= 00
Private CONTFL     	:= 01
Private m_pag      	:= 01
Private wnrel      	:= "PEFINREL" 

//ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
//³Chama função para monitor uso de fontes customizados³
//ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
U_USORWMAKE(ProcName(),FunName())

wnrel := SetPrint("",NomeProg,"",@titulo,cDesc1,cDesc2,cDesc3,.F.,aOrd,.F.,Tamanho,,.F.)

If nLastKey == 27
	Return
Endif

SetDefault(aReturn,"")

If nLastKey == 27
   Return
Endif

nTipo := If(aReturn[4]==1,15,18)

RptStatus({|| RunReport(Cabec1,Cabec2,Titulo,nLin) },Titulo)
Return


Static Function RunReport(Cabec1,Cabec2,Titulo,nLin)

Local nOrdem



For nR := 1 To Len(_aErros)

    If lAbortPrint
       @nLin,00 PSAY "*** CANCELADO PELO OPERADOR ***"
       Exit
    Endif

    If nLin > 60
       Cabec(Titulo,Cabec1,Cabec2,NomeProg,Tamanho,nTipo)
       nLin := 9
    Endif

//	_cTitulo,_cParc,_cCli,_cLoja,_cErros,_TpMov
	@nLin, 000 Psay _aErros[nR,1]
	@nLin, 007 Psay _aErros[nR,2]
	@nLin, 010 Psay _aErros[nR,3]
	@nLin, 017 Psay _aErros[nR,4]
	DbSelectArea("SA1")
	SA1->(DbGotop())
	SA1->(DbSetOrder(1))
	DbSeek(xFilial("SA1")+_aErros[nR,3]+_aErros[nR,4])
	@nLin, 030 Psay SubStr(SA1->A1_NOME,1,25)
	If AllTrim(_aErros[nR,5])	== "INCLUSAO OK" .OR. AllTrim(_aErros[nR,5]) == "EXCLUSAO OK"
		@nLin, 057 Psay _aErros[nR,5]
	Else
		@nLin, 057 Psay "OS ERROS ABAIXO FORAM ENCONTRADOS"
		nLin += 1
	    If nLin > 60
	       Cabec(Titulo,Cabec1,Cabec2,NomeProg,Tamanho,nTipo)
	       nLin := 9
	    Endif		
		nErr	:= 1
		For nX := 1 To (Len(AllTrim(_aErros[nR,5]))/3)
			If nX = 1
				@nLin, 030 Psay SubStr(_aErros[nR,5],nX,3)
				@nLin, 034 Psay AllTrim(PefinErr(SubStr(_aErros[nR,5],nX,3)))
			Else
				@nLin, 020 Psay SubStr(_aErros[nR,5],nErr,3)			
				@nLin, 024 Psay AllTrim(PefinErr(SubStr(_aErros[nR,5],nErr,3)))				
			Endif
			nErr += 3
			nLin += 1
		    If nLin > 60
		       Cabec(Titulo,Cabec1,Cabec2,NomeProg,Tamanho,nTipo)
		       nLin := 9
		    Endif						
		Next nX 
	Endif
	nLin += 1

Next nR

SET DEVICE TO SCREEN

If aReturn[5]==1
   dbCommitAll()
   SET PRINTER TO
   OurSpool(wnrel)
Endif

MS_FLUSH()

Return

Static Function PefinErr(_cErro)
Local aErros := {}
Local cRerro := ""

aAdd(aErros,{"001","ARQUIVO SEM DETALHES"})
aAdd(aErros,{"002","PRIMEIRO REGISTRO NAO E HEADER/SEQUENCIA DIFERENTE DE 1"})
aAdd(aErros,{"003","REGISTRO DIFERENTE DE 0, 1 E 9"})
aAdd(aErros,{"004","REGISTRO FORA DE SEQUENCIA"})
aAdd(aErros,{"005","REGISTRO TRAILLER NAO INFORMADO"})
aAdd(aErros,{"008","CODIGO DE OPERACAO DIFERENTE DE E, I"})
aAdd(aErros,{"009","TIPO DE PESSOA PRINCIPAL DIFERENTE DE F, J"})
aAdd(aErros,{"010","TIPO DE PESSOA COOBRIGADO DIFERENTE DE F, J"})
aAdd(aErros,{"011","NOME INVALIDO"})
aAdd(aErros,{"012","NOME NAO PODE SER BRANCOS"})
aAdd(aErros,{"013","DATA DO HEADER INVALIDA"})
aAdd(aErros,{"014","DATA DA OCORRENCIA INVALIDA"})
aAdd(aErros,{"016","DATA DA OCORRENCIA MAIOR QUE A ATUAL"})
aAdd(aErros,{"017","DATA DA OCORRENCIA JA DECURSADA"})
aAdd(aErros,{"018","IDENTIFICACAO DO ARQUIVO INVALIDA"})
aAdd(aErros,{"019","REMESSA NAO POSTERIOR A ULTIMA"})
aAdd(aErros,{"020","REMESSA NAO NUMERICA OU IGUAL A ZERO"})
aAdd(aErros,{"021","CAMPO DE RECEBIMENTO DA REMESSA DIFERENTE DE 'E'"})
aAdd(aErros,{"022","EXCLUSAO PARA REGISTRO INEXISTENTE"})
aAdd(aErros,{"024","CNPJ DO HEADER INVALIDO"})
aAdd(aErros,{"025","CNPJ NAO CADASTRADO NO SISTEMA (TABELA DE REMESSA)"})
aAdd(aErros,{"026","FILIAL DA INSTITUICAO NAO NUMERICA"})
aAdd(aErros,{"027","FILIAL DA INSTITUICAO INVALIDA"})
aAdd(aErros,{"028","DOCUMENTO DO PRINCIPAL NAO NUMERICO"})
aAdd(aErros,{"029","DOCUMENTO DO PRINCIPAL INVALIDO"})
aAdd(aErros,{"030","DOCUMENTO DO COOBRIGADO NAO NUMERICO"})
aAdd(aErros,{"031","DOCUMENTO DO COOBRIGADO INVALIDO"})
aAdd(aErros,{"033","TRAILLER FORA DE SEQUENCIA"})
aAdd(aErros,{"034","SEQUENCIA NAO NUMERICA"})
aAdd(aErros,{"035","NATUREZA INVALIDA"})
aAdd(aErros,{"036","NATUREZA INVALIDA PARA O CNPJ INFORMADO"})
aAdd(aErros,{"037","PRACA INVALIDA"})
aAdd(aErros,{"040","REG. NAO ATUALIZADO. ERRO NO PRINCIPAL OU COOBRIGADO DA OCORRENCIA"})
aAdd(aErros,{"044","AGENCIA INVALIDA"})
aAdd(aErros,{"047","CONTA NAO NUMERICA"})
aAdd(aErros,{"059","INCLUSAO PARA REGISTRO JA EXISTENTE"})
aAdd(aErros,{"064","CONTA INVALIDA"})
aAdd(aErros,{"065","CHEQUE INVALIDO"})
aAdd(aErros,{"072","ALINEA INVALIDA"})
aAdd(aErros,{"081","REGISTRO APOS TRAILLER"})
aAdd(aErros,{"085","NUMERO DO CONTRATO/TITULO INVALIDO"})
aAdd(aErros,{"089","EMPRESA NAO PARTICIPANTE DO CONVENIO"})
aAdd(aErros,{"101","DATA DE NASCIMENTO EH OBRIGATORIA/INVALIDA"})
aAdd(aErros,{"102","NUMERO DO CONTRATO/TITULO EH OBRIGATORIO"})
aAdd(aErros,{"103","TIPO DE DOCUMENTO INVALIDO"})
aAdd(aErros,{"105","INCLUSAO BLOQUEADA FACE A DETERMINACAO ADMINISTRATIVA"})
aAdd(aErros,{"106","MOVIMENTO APOS RESCISAO DE CONTRATO DO CONVENIO"})
aAdd(aErros,{"109","FALTA ENDERECO"})
aAdd(aErros,{"111","FALTA UF DO ENDERECO"})
aAdd(aErros,{"112","FALTA CEP DO ENDERECO"})
aAdd(aErros,{"113","FALTA INFORMACAO TIPO DE PESSOA"})
aAdd(aErros,{"115","TIPO DE PESSOA DO PRINCIPAL DIFERENTE DE F"})
aAdd(aErros,{"116","TIPO DE PESSOA DO COOBRIGADO DIFERENTE DE F"})
aAdd(aErros,{"119","CEP DO ENDERECO INVALIDO"})
aAdd(aErros,{"121","DATA DE NASCIMENTO INFERIOR A 18 ANOS"})
aAdd(aErros,{"142","BANCO NAO TRABALHA COM CONTA CORRENTE"})
aAdd(aErros,{"156","DATA OCORRENCIA INFERIOR A 4 DIAS"})
aAdd(aErros,{"165","DT.TERMINO DO CONTRATO ANTERIOR A DT. DA OCORRENCIA"})
aAdd(aErros,{"166","DATA DE TERMINO DO CONTRATO INVALIDA"})
aAdd(aErros,{"167","FALTA UF DO RG"})
aAdd(aErros,{"168","VALOR DEVE SER NUMERICO E MAIOR QUE ZEROS"})
aAdd(aErros,{"169","AREA INFORMANTE DA REMESSA C/ ERRO. MOVIMENTO REJEITADO"})
aAdd(aErros,{"170","BANCO INVAL. P/ NATUREZA DE/DC"})
aAdd(aErros,{"171","TIPO DE PESSOA DO CREDOR DIFERENTE DE F, J"})
aAdd(aErros,{"172","TIPO DE DOCUMENTO DO CREDOR INVALIDO"})
aAdd(aErros,{"173","DOCUMENTO DO CREDOR NAO NUMERICO"})
aAdd(aErros,{"174","DOCUMENTO DO CREDOR INVALIDO"})
aAdd(aErros,{"175","NOME DO CREDOR EH OBRIGATORIO"})
aAdd(aErros,{"176","NOME DO CREDOR INVALIDO"})
aAdd(aErros,{"177","FOI INFORMADO O CREDOR. PARTICIPANTE NAO EH ENTIDADE DE CLASSE"})
aAdd(aErros,{"181","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. MUDOU-SE"})
aAdd(aErros,{"182","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. ENDERECO INSUFICIENT"})
aAdd(aErros,{"183","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. NUMERO INEXISTENTE"})
aAdd(aErros,{"184","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. DESCONHECIDO"})
aAdd(aErros,{"185","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. RECUSADO"})
aAdd(aErros,{"186","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. NAO PROCURADO"})
aAdd(aErros,{"187","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. AUSENTE"})
aAdd(aErros,{"188","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. FALECIDO"})
aAdd(aErros,{"189","EXCL.DEVIDO DEVOL.COMUNICADO PELO CORREIO.INFOR.PORTEIRO/SINDICO"})
aAdd(aErros,{"190","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. ENDERECO DESCONHECIDO"})
aAdd(aErros,{"191","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. CEP INCORRETO"})
aAdd(aErros,{"192","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. NAO ESPECIFICADO"})
aAdd(aErros,{"193","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. CX POSTAL INEXISTENTE"})
aAdd(aErros,{"194","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO. IMOVEL INEXISTENTE"})
aAdd(aErros,{"195","EXCL. DEVIDO DEVOL. COMUNICADO PELO CORREIO"})
aAdd(aErros,{"196","INCLUSAO RECUSADA/CARTA DEVOLVIDA DO CORREIO/END.IGUAL AO ANTERIOR"})
aAdd(aErros,{"197","ENDERECO ALTERNATIVO SOLICITADO PELA CONTRATANTE"})
aAdd(aErros,{"219","VALOR DO TITULO INVALIDO"})
aAdd(aErros,{"263","IDENTIFICACAO DO ARQUIVO INVALIDA"})
aAdd(aErros,{"274","CNPJ NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DAT"})
aAdd(aErros,{"275","CPF NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA"})
aAdd(aErros,{"276","FILIAL NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA"})
aAdd(aErros,{"277","CNPJ CREDOR/CEDENTE NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DAT"})
aAdd(aErros,{"278","CPF CREDOR/CEDENTE NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA"})
aAdd(aErros,{"279","FILIAL CREDOR/CEDENTE NAO EXISTE CADASTRO DE CNPJ/CPF ATE ESTA DAT"})
aAdd(aErros,{"286","DOCUMENTO DO CREDOR IGUAL AO DO NEGATIVADO"})
aAdd(aErros,{"289","INFORMADO A UF SEM O NUMERO DO RG"})
aAdd(aErros,{"290","EXCLUSAO POR DATA DE OCORRENCIA JA DECURSADA"})
aAdd(aErros,{"291","EXCLUSAO POR DETERMINACAO JUDICIAL"})
aAdd(aErros,{"292","EXCLUSAO POR SOLICITACAO DA EMPRESA PARTICIPANTE"})
aAdd(aErros,{"295","RAZAO SOCIAL NAO CORRESPONDE AO CNPJ INFORMADO"})
aAdd(aErros,{"296","NOME NAO CORRESPONDE AO CPF INFORMADO"})
aAdd(aErros,{"298","COOBRIGADO NAO INCLUIDO - PRINCIPAL NAO ENCONTRADO"})
aAdd(aErros,{"301","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - MUDOU-SE"})
aAdd(aErros,{"302","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - END INSUFICIENTE"})
aAdd(aErros,{"303","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - NR INEXISTENTE"})
aAdd(aErros,{"304","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - DESCONHECIDO"})
aAdd(aErros,{"305","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - RECUSADO"})
aAdd(aErros,{"306","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - NAO PROCURADO"})
aAdd(aErros,{"307","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - AUSENTE"})
aAdd(aErros,{"308","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - FALECIDO"})
aAdd(aErros,{"309","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - INFORM P/ PORTEIRO"})
aAdd(aErros,{"310","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - END N CONHECIDO"})
aAdd(aErros,{"311","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - CEP INCORRETO"})
aAdd(aErros,{"312","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - N ESPECIFICADO"})
aAdd(aErros,{"313","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - CX POSTAL INEXIST"})
aAdd(aErros,{"314","REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - IMOVEL INEXISTENTE"})
aAdd(aErros,{"315","DEVIDO A DEVOLUCAO DO COMUNICADO DO CORREIO"})
aAdd(aErros,{"356","DATA DO COMPROMISSO MAIOR QUE A ATUAL"})
aAdd(aErros,{"357","DATA DO COMPROMISSO INVALIDA"})
aAdd(aErros,{"358","VALOR DO COMPROMISSO NAO NUMERICO"})
aAdd(aErros,{"359","DDD DEVE SER NUMERICO"})
aAdd(aErros,{"360","TELEFONE DEVE SER NUMERICO"})
aAdd(aErros,{"381","INCLUSAO REJEITADA - VLR CONSID.ELEVADO - INCLUIR PELO SISCONVEM"})
aAdd(aErros,{"390","INCLUSAO RECUSADA - PARTICIPANTE COM LOGON BLOQUEADO"})
aAdd(aErros,{"391","REGISTRO REJEITADO - INCONSISTENCIA NO HEADER"})
aAdd(aErros,{"392","FALTA CODIGO CLIENTE NA RSREMESSA OU CODIGO NAO TEM 5 CARACTERE"})
aAdd(aErros,{"393","FALTA PROCNAME NA RSREMESS OU PROCNAME NAO TEM 8 CARACTERS"})
aAdd(aErros,{"394","CNPJ NAO CORRESPONDE AO CODIGO DE CLIENTE INFORMADO"})
aAdd(aErros,{"396","INCLUSAO REJEITADA-VLR.CONS.ELEVADO-NEGAT.PRIMARIA-INCL.SISCONVEM"})
aAdd(aErros,{"397","VLR CONSID ELEVADO-NEGAT PRIMARIA-REDIGITAR O VALOR"})
aAdd(aErros,{"429","PROCNAME (REMESSA) INVALIDO - TAMANHO DO REGISTRO ERRADO"})
aAdd(aErros,{"430","PROCNAME (REMESSA) INVALIDO - TIPO DE TRANSMISSAO ERRADO"})
aAdd(aErros,{"443","EXCLUSAO POR CONTESTACAO/DECLARACAO DO INTERESSADO"})
aAdd(aErros,{"465","DATA DO CANCELAMENTO DO CONTRATO NAO INFORMADA"})
aAdd(aErros,{"466","EXCLUSAO POR FALTA DE DOCUMENTACAO DA DIVIDA"})
aAdd(aErros,{"488","PARTICIPANTE NAO CURACAO DO CREDOR"})
aAdd(aErros,{"489","UF DO RG INVALIDO"})
aAdd(aErros,{"490","FALTAM DADOS CADASTRAIS DO CREDOR DA DIVIDA"})
aAdd(aErros,{"491","MUNICIPIO NAO CORRESPONDE AO CEP E/OU UF INFORMADO"})
aAdd(aErros,{"495","PRO-REDE - NAO LOCALIZADO O ENDERECO DO CREDOR"})
aAdd(aErros,{"609","EXCLUSAO - CARTA COMUNICADO/COMPROVANTE NAO RETORNOU DOS CORREIOS"})
aAdd(aErros,{"610","INCLUSAO CONDICIONADA A APRESENTACAO DE DOCTO DA DIVIDA"})
aAdd(aErros,{"611","LOGON INFORMADO NO HEADER NAO PERTENCE AO PARTICIPANTE"})
aAdd(aErros,{"612","LOGON INFORMADO NO HEADER NAO ENCONTRADO"})
aAdd(aErros,{"620","SCORE NAO CALCULADO POR SOLICITACAO DO CLIENTE, ANOTACAO NAO INCLUIDA"})
aAdd(aErros,{"621","SCORE ACIMA DO PERMITIDO, ANOTACAO NAO INCLUIDA"})
aAdd(aErros,{"650","CODIGO DO BANCO INVALIDO"})
aAdd(aErros,{"651","BANCO NÃO CADASTRADO"})
aAdd(aErros,{"652","DIGITO DO CODIGO DO BANCO INVALIDO"})
aAdd(aErros,{"653","NOME DO BANCO NÃO INFORMADO"})
aAdd(aErros,{"654","CARACTERES DA LINHA DIGITAVEL INVALIDA"})
aAdd(aErros,{"655","PRIMEIRO DIGITO DA LINHA DIGITAVEL DIVERGENTE"})
aAdd(aErros,{"656","SEGUNDO DIGITO DA LINHA DIGITAVEL DIVERGENTE"})
aAdd(aErros,{"657","TERCEIRO DIGITO DA LINHA DIGITAVEL DIVERGENTE"})
aAdd(aErros,{"658","QUARTO DIGITO DA LINHA DIGITAVEL DIVERGENTE"})
aAdd(aErros,{"659","TEXTO DO LOCAL DE PAGAMENTO NÃO INFORMADO"})
aAdd(aErros,{"660","DATA DE VENCIMENTO DO BOLETO INVALIDA"})
aAdd(aErros,{"661","DATA DE VENCIMENTO DO BOLETO MENOR QUE A DATA DE HOJE"})
aAdd(aErros,{"662","TIPO DE PESSOA DO DOCUMENTO DO CEDENTE INVALIDO"})
aAdd(aErros,{"663","TIPO DE DOCUMENTO  DO CEDENTE DIVERGENTE DO TIPO DE PESSOA"})
aAdd(aErros,{"664","DOCUMENTO DO CEDENTE INVALIDO"})
aAdd(aErros,{"665","DIGITO DO DOCUMENTO DO CEDENTE INVALIDO"})
aAdd(aErros,{"666","AGENCIA E CODIGO DO CEDENTE NÃO INFORMADO"})
aAdd(aErros,{"667","DATA DO DOCUMENTO INVALIDA"})
aAdd(aErros,{"668","NUMERO DO DOCUMENTO NÃO INFORMADO"})
aAdd(aErros,{"669","DATA DO PROCESSAMENTO INFORMADA E INVALIDA"})
aAdd(aErros,{"670","NOSSO NUMERO NÃO INFORMADO"})
aAdd(aErros,{"671","QUANTIDADE DE MOEDA NÃO INFORMADA"})
aAdd(aErros,{"672","QUANTIDADE DE MOEDA INVALIDA"})
aAdd(aErros,{"673","QUANTIDADE DE DECIMAIS DA MOEDA NÃO INFORMADA"})
aAdd(aErros,{"674","QUANTIDADE DE DECIMAIS DA MOEDA INVALIDA"})
aAdd(aErros,{"675","QUANTIDADE DE DECIMAIS DA MOESA MAIOR QUE 5 CASAS DECIMAIS"})
aAdd(aErros,{"676","VALOR DA MOEDA NÃO INFORMADO"})
aAdd(aErros,{"677","VALOR DA MOEDA INVALIDA"})
aAdd(aErros,{"678","VALOR DO DOCUMENTO INVALIDO"})
aAdd(aErros,{"679","VALOR DE OUTROS ACRESCIMOS INVALIDO"})
aAdd(aErros,{"680","VALOR DE DESCONTOS/ABATIMENTO INVALIDO"})
aAdd(aErros,{"681","VALOR DE OUTRAS DEDUCOES INVALIDO"})
aAdd(aErros,{"682","VALOR DE MORA/MULTA INVALIDO"})
aAdd(aErros,{"683","VALOR COBRADO INVALIDO"})
aAdd(aErros,{"684","TIPO DE PESSOA DO DOCUMENTO DO SACADOR INVALIDO"})
aAdd(aErros,{"685","TIPO DE DOCUMENTO  DO SACADOR DIVERGENTE DO TIPO DE PESSOA"})
aAdd(aErros,{"686","DOCUMENTO DO SACADOR INVALIDO"})
aAdd(aErros,{"687","DIGITO DO DOCUMENTO DO SACADOR INVALIDO"})
aAdd(aErros,{"701","EXISTE DADOS DE BOLETO E NAO INFORMADO O INDICATIVO DE TIPO DE COMUNICADO"})
aAdd(aErros,{"702","INDICATIVO DE TIPO DE COMUNICADO DIFERENTE DE BRANCO OU 'B' "})
aAdd(aErros,{"703","TIPO DE COMUNICADO COMO BOLETO E NÃO FOI INFORMADO O REG. TP 2 E/OU 3"})
aAdd(aErros,{"704","TIPO DE COMUNICADO BOLETO NÃO PERMITIDO PARA COOBRIGADO"})
aAdd(aErros,{"705","REG BOLETO TIPO 2 ENCONTRADO, SEM REGISTRO TIPO 1 CORRESPONDENTE"})
aAdd(aErros,{"706","REG BOLETO TIPO 3 ENCONTRADO, SEM REGISTRO TIPO 1 CORRESPONDENTE"})
aAdd(aErros,{"707","PARTICIPANTE NAO POSSUI CONTRATO PARA EMISSAO DE COMUNICADO COM BOLETO"})
nPosicao  := ascan(aErros,{|_x| _cErro == _x[1]})
cRet	  := aErros[nPosicao,2]

Return(cRet)
