#include "rwmake.ch"
#include "protheus.ch"

/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณMA261D3   บ Autor ณ Rafael Parma       บ Data ณ  07/12/10   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDescricao ณ Ponto de entrada utilizado para gravar o c๓digo da classe  บฑฑ
ฑฑบ          ณ de valor sobre as movimenta็๕es de transferencias mod II.  บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ RJU                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/
*---------------------------*
User Function MA261D3()     
*---------------------------*
Local aAreaTMP := GetArea()
Local nRECNTMP := SD3->(RECNO())
Private cMV_XARXCV := ALLTRIM(SuperGetMV("MV_X_ARXCV",,""))
Private cFILNUMSEQ := SD3->D3_FILIAL+SD3->D3_NUMSEQ   

//ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
//ณChama fun็ใo para monitor uso de fontes customizadosณ
//ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
U_USORWMAKE(ProcName(),FunName())
	
	dbSelectArea("SD3")
	dbSetOrder(4)	//D3_FILIAL+D3_NUMSEQ+D3_CHAVE+D3_COD
	dbGoTop()
	If dbSeek ( cFILNUMSEQ )
		While !SD3->(EOF()) .and. SD3->D3_FILIAL+SD3->D3_NUMSEQ == cFILNUMSEQ			
			If SD3->D3_LOCAL $ cMV_XARXCV
				If RecLock("SD3",.F.)
					SD3->D3_CLVL := fGetCLVL(SD3->D3_LOCAL, cMV_XARXCV)
					SD3->(MsUnLock())
				EndIf
			EndIf
			SD3->(dbSkip())
		Enddo	
	EndIf      

	dbSelectArea("SD3")
	dbGoTo(nRECNTMP)   
	
	RestArea(aAreaTMP)

Return 
/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณfGetCLVL  บ Autor ณ Rafael Parma       บ Data ณ  07/12/10   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDescricao ณ Fun็ใo auxiliar para recuperar c๓digo classe de valor.     บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ RJU                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/
*--------------------------------------------*
Static Function fGetCLVL(cLOCAL, cFILNUMSEQ)
*--------------------------------------------*
Local cRET := ""
Local cAUX := ""
Local lAUX := .F.

	For nI := 1 to Len(cFILNUMSEQ)
		If ! SubSTR(cFILNUMSEQ,nI,1) $ "=/"
			cAUX += SubSTR(cFILNUMSEQ,nI,1)
		ElseIf SubSTR(cFILNUMSEQ,nI,1) == "="
			If ! lAUX 
				If cAUX == cLOCAL
					lAUX := .T.
				EndIf
				cAUX := ""
			EndIf
		ElseIf SubSTR(cFILNUMSEQ,nI,1) == "/"
			If ! lAUX 
				cAUX := ""
			Else
				Exit
			EndIf
		EndIf
	Next nI
	
	If lAUX
		cRET := cAUX
	EndIf

Return (cRET)