#INCLUDE "PROTHEUS.CH"


/*/{Protheus.doc} User Function FA60BDE
    (long_description)
    @type  Function
    @author August Ribeiro
    @since 15/04/2020
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
User Function FA60TRAN ()
	
    /*--------------------------------------------------------------------------
		FATURAMENTO AUTOMÁTICO - ESTORNA TABELA DE RANGE
	--------------------------------------------------------------------------*/
    U_FSFATJCA()


Return()